services:
  mysql:
    image: mysql:8.0
    container_name: photo_service_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: photo_service_db
      MYSQL_USER: photo_user
      MYSQL_PASSWORD: photo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - photo_service_network

  app:
    build: .
    container_name: photo_service_app
    environment:
      DATABASE_HOST: mysql
    ports:
      - "3000:3000"  # Exposes your NestJS app
    depends_on:
      - mysql
    networks:
      - photo_service_network
    command: npm run start

volumes:
  mysql_data:
    driver: local

networks:
  photo_service_network:
    driver: bridge
