services:
  mysql:
    image: mysql:8.0
    container_name: photo_service_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: photo_service_db
      MYSQL_USER: photo_user
      MYSQL_PASSWORD: photo_password
    ports:
      - "3306:3306"
    networks:
      - photo_service_network

  app:
    build: .
    container_name: photo_service_app
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
    depends_on:
      - mysql
    command: ["sh", "-c", "wait-for-it.sh mysql:3306 -- npm run start"]
    networks:
      - photo_service_network

networks:
  photo_service_network:
    driver: bridge
